---
- name: Pull Docker Image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: rakshitbang099/sportech_frontend:latest
        source: pull

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -d --name Sportech-Frontend rakshitbang099/sportech_frontend:latest

    - name: Wait for container to be ready
      wait_for:
        host: localhost
        port: 3000

    - name: Install firebase cli
      shell: docker exec Sportech-Frontend npm install -g firebase-tools

    - name: Find path to firebase CLI
      shell: docker exec Sportech-Frontend which firebase
      register: firebase_path

    - name: deploy npm app
      shell: docker exec Sportech-Frontend {{ firebase_path.stdout }} deploy
    
    - name: docker stop
      shell: docker stop Sportech-Frontend
