---
- name: Pull Docker Image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: rakshitbang099/sportech_frontend:latest
        source: pull

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -d --name Sportech-Frontend rakshitbang099/sportech_frontend 

    - name: Install firebase cli
      shell: docker exec -it Sportech-Frontend npm install firebase-tools

    - name: deploy npm app
      shell: docker exec -it Sportech-Frontend firebase deploy